---
name: Rust
on:
  push:
    branches: [build-on-macos]

permissions:
  contents: read
  statuses: write

env:
  CARGO_TERM_COLOR: always
  # Minimum supported Rust version (MSRV)
  ACTIONS_MSRV_TOOLCHAIN: 1.44.1
  # Pinned toolchain for linting
  ACTIONS_LINTS_TOOLCHAIN: 1.52.0

jobs:
  tests-stable:
    name: "Tests, stable toolchain"
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "stable"
          default: true
      - name: cargo build
        run: cargo build
      - name: cargo test
        run: cargo test
      - name: cargo build (rdcore)
        run: cargo build --features rdcore
      - name: cargo test (rdcore)
        run: cargo test --features rdcore
